name: Create Zip
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Folder
      run: zip -r items.zip assets/ pack.png pack.mcmeta 
    - name: Release to Github
      run: echo "Release"
    - name: Upload Release
      uses: ncipollo/release-action@master
      with:
        artifacts: "items.zip"
        token: ${{ secrets.GITHUB_TOKEN }} 
       